<?php
/**
 * This code was generated by Darling Cms App Manager app.
 */

namespace Apps\PHPMyAdminFrame;

use DarlingCms\interfaces\accessControl\IAppConfig;

class AppConfig implements IAppConfig
{
    /**
     * Validates access.
     * @return bool True if access is valid, false otherwise.
     */
    public function validateAccess(): bool
    {
        // WARNING! Only run on localhost!!!!!!!!
        //var_dump(substr("http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]", 0, 32) === 'http://localhost:8888/DarlingCms');
        if (substr("http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]", 0, 32) === 'http://localhost:8888/DarlingCms') {
            return true;
        }
        return false;
    }

    /**
     * Gets the app's name.
     * @return string The app's name.
     */
    public function getName(): string
    {
        return 'PHPMyAdminFrame';
    }

    /**
     * Gets an array of the names of the themes assigned to the app.
     * @return array Array of the names of the themes assigned to the app.
     */
    public function getThemeNames(): array
    {
        return array();
    }

    /**
     * Gets an array of the names of the javascript libraries assigned to the app.
     * @return array Array of the names of the javascript libraries assigned to the app.
     */
    public function getJsLibraryNames(): array
    {
        return array('makeDraggable');
    }
}
