<?php
/**
 * This code was generated by Darling Cms App Manager app.
 */

namespace Apps\UserManager;

use DarlingCms\abstractions\accessControl\AAdminAppConfig;
use DarlingCms\classes\accessControl\UserLogin;
use DarlingCms\classes\factory\CoreMySqlCrudFactory;
use DarlingCms\interfaces\accessControl\IAppConfig;

class AppConfig extends AAdminAppConfig implements IAppConfig
{
    /**
     * Validates access.
     * @return bool True if access is valid, false otherwise.
     */
    public function validateAccess(): bool
    {
        return parent::validateAccess();
    }

    /**
     * Gets the app's name.
     * @return string The app's name.
     */
    public function getName(): string
    {
        return 'UserManager';
    }

    /**
     * Gets an array of the names of the themes assigned to the app.
     * @return array Array of the names of the themes assigned to the app.
     */
    public function getThemeNames(): array
    {
        return array('UserManager');
    }

    /**
     * Gets an array of the names of the javascript libraries assigned to the app.
     * @return array Array of the names of the javascript libraries assigned to the app.
     */
    public function getJsLibraryNames(): array
    {
        return array('AjaxRouter');
    }
}
